=== gzhu108/sg/example/myserver/raml/schema/rule.json
{
    "type": "object",
    "$schema": "http://json-schema.org/draft-03/schema",
    "required": false,
    "properties": {
        "countryCode": {
            "type": "string",
            "final": true
        },
        "ruleId": {
            "type": "string",
            "required": true
        },
        "paymentType": {
            "type": "string",
            "required": false
        },
        "paymentMethod": {
            "type": "string",
            "required": false
        },
        "binStart": {
            "type": "string",
            "required": false
        },
        "binEnd": {
            "type": "string",
            "required": false
        },
        "distributions": {
            "type": "array",
            "required": false,
            "maxItems": 10,
            "items": {
                "$ref": "distribution#"
            }
        }
    }
}

=== gzhu108/sg/example/myserver/raml/example/rule.json
{
    "countryCode": "US",
    "ruleId": "123e4567-e89b-12d3-a456-426655440000",
    "paymentType": "CC",
    "paymentMethod": "VISA",
    "binStart": "123456",
    "binEnd": "123456",
    "distributions": [
        {
            "vendorId": 1,
            "percentage": 60
        },
        {
            "vendorId": 2,
            "percentage": 40
        }
    ]
}
